const SALES_STAGE_CATALOG = [
  {
    code: "nuevo_lead",
    name: "Nuevo lead",
    sortOrder: 10,
    isClosedWon: false,
    isClosedLost: false,
    description: "Lead recien captado, aun sin calificacion comercial.",
  },
  {
    code: "contactado",
    name: "Contactado",
    sortOrder: 20,
    isClosedWon: false,
    isClosedLost: false,
    description: "Ya hubo primer contacto o respuesta inicial.",
  },
  {
    code: "interesado",
    name: "Interesado",
    sortOrder: 30,
    isClosedWon: false,
    isClosedLost: false,
    description: "El prospecto mostro interes real o senales claras de compra.",
  },
  {
    code: "cotizacion_enviada",
    name: "Cotizacion enviada",
    sortOrder: 40,
    isClosedWon: false,
    isClosedLost: false,
    description: "Ya recibio propuesta, catalogo o precio formal.",
  },
  {
    code: "esperando_confirmacion",
    name: "Esperando confirmacion",
    sortOrder: 50,
    isClosedWon: false,
    isClosedLost: false,
    description: "Hay interes, pero aun faltan confirmaciones comerciales para avanzar.",
  },
  {
    code: "pendiente_comprobante",
    name: "Pendiente de comprobante",
    sortOrder: 60,
    isClosedWon: false,
    isClosedLost: false,
    description: "El cliente pagara por transferencia y aun falta el comprobante.",
  },
  {
    code: "validando_pago",
    name: "Validando pago",
    sortOrder: 70,
    isClosedWon: false,
    isClosedLost: false,
    description: "El comprobante ya llego y el pago esta en revision.",
  },
  {
    code: "pedido_confirmado",
    name: "Pedido confirmado",
    sortOrder: 80,
    isClosedWon: false,
    isClosedLost: false,
    description: "El pedido ya quedo confirmado y puede pasar a operacion.",
  },
  {
    code: "preparando_entrega",
    name: "Preparando entrega",
    sortOrder: 90,
    isClosedWon: false,
    isClosedLost: false,
    description: "El pedido esta en preparacion o alistamiento para despacho.",
  },
  {
    code: "en_ruta",
    name: "En ruta",
    sortOrder: 100,
    isClosedWon: false,
    isClosedLost: false,
    description: "El pedido ya va camino al domicilio de entrega.",
  },
  {
    code: "entregado",
    name: "Entregado",
    sortOrder: 110,
    isClosedWon: true,
    isClosedLost: false,
    description: "La entrega se completo y el pedido ya fue recibido.",
  },
  {
    code: "entrega_fallida",
    name: "Entrega fallida",
    sortOrder: 120,
    isClosedWon: false,
    isClosedLost: true,
    description: "La entrega no se pudo completar y requiere accion correctiva.",
  },
  {
    code: "cancelado",
    name: "Cancelado",
    sortOrder: 130,
    isClosedWon: false,
    isClosedLost: true,
    description: "La oportunidad o el pedido ya no seguiran activos.",
  },
];

module.exports = {
  SALES_STAGE_CATALOG,
};
